---
title: "Reviewer Response"
output:
  word_document: default
  html_document:
    df_print: paged
---


Dear Editor,

Thank you for sending review reports for our manuscript. The previous round of reviewer comments greatly improved the manuscript. The reviewer comments from this round were again useful and have led to further improvements.

We enclose a revised version of the manuscript (clean and with tracked changes), which addresses the reviewer’s comments and suggestions. The reviewer’s comments are shown below with our response to each comment in italics.

Yours sincerely,

Sam Abbott

## Authors' response to Reviewer #1

The manuscript has been improved and most of my comments have been addressed.

*Thank you for taking the time to review the manuscript again and for your comments.*

I have only a few minor suggestions: 
The abbreviation 'JCVI' is still spelt wrong in many parts of the manuscript, including figure legends. I suggest the authors run a thorough check. 

*Thank you for highlighting this mistake and apologies that it was not dealt with correctly in the last round of responses - we have thoroughly checked the manuscript and corrected misspellings.*

It seems to me that the two method sections - 'estimating notification rates' and 'construction of forward estimates' - are the content of Sutherland et al.'s model. If they are, marking the origin explicitly (potentially in the section titles) may help the audience to compare between the original and updated methods. Or if the original and updated methods are both involved in these two sections, please state the difference more explicitly. 


*We have marked these sections as original (to match the approach used for the transmission model.*

In 'Original transmission chain model' section, I found the notations 'T' confusing, as they appear in both steps 1. and 2. but come with different definitions. Although this may be the original way how the Sutherland et al.'s model was presented, do you consider to assign different notations or add subscripts to them for clarification? 

*We have standardised the definitions used for T in 1. and 2. *

In 'Model assumptions' of supplementary information, the notation 'T' is used but without further definition. As there are two definitions for 'T' used in the main text (as mentioned in the above point), it will be helpful to define the notation again here or make it clearly linked back to the definition in the main text. 

*We have added the standardised definition now used in both 1. and 2. to this section along with the definition for $x$.*

## Authors' response to Reviewer #2

OVERALL 

I appreciate the effort made by the authors to improve the clarity and respond to my comments. I find the article is now much easier to follow, and should be published after a few minor revisions. 

*Thank you for reviewing the updated manuscript and for your suggested revisions. We agree that the last set of revisions substantially improved the manuscript.*

SPECIFIC 

- Abstract. I find the Conclusions a bit long and containing Results. I would suggest moving the first two sentences of the current Conclusions up into Results to have a punchier summary & implication in the Conclusions. Also: can you be more specific about the meaning of 'most comparable to notification data'? 

*As suggested we have moved the first two sentences of the conclusions into the results section, editing them to avoid repetition. We have reworded 'most comparable to notification data' to make it clear that model estimates based on an assumed decrease in TB are being compared to model estimates derived using notification data.*

- Strengths & limitations bullets. 'our results are conservative' - I don't find it obvious what this means. Which results, and which direction does 'conservative' mean in this case? (Eg result could be referring to the NNV, although I wouldn't be certain which direction conservative would then mean; could be cases caused by change, in which case conservative means this could be larger; or could be talking about the increase in uncertainty.) 

*We have reworded this sentence (and the corresponding sentence in the discussion) to indicate that we think that excluding these factors may mean our results underestimate the impact of ending the BCG schools scheme.*

- Model description in text. This is now much clearer. There are a few minor suggestions for the section on Updating the transmission chain model. 

In this section, 'secondary cases' refers (in introducing z) to those directly resulting in the next generation. In bullet 3 introducing Z, all secondary cases are considered. Suggest using more specific phraseology, eg '(secondary) cases in the next generation' where it applies. 

*We have updated the text to use the more specifc phraseology suggested.*

Related to this perhaps, I didn't understand the bit about not being able to 'estimate when secondary notifications occurred' when you have just defined them as z years later, or if they are not the next generation cases you have a distribution implied by bullet point defining Z. If this isn't important and keeping them in the same year as root cases just facilitates book-keeping, then this should come across. 

*This statement was intended to indicate that our approach could not allocate cases annually (only by generation or overall). This step was neccessary in order to completely reproduce the previously published results but does not impact estimates of the overall impact of ending the scheme. We have clarified this both in the methods section and in the SI.*

Also around here, referring to x as the 'initial generation size' leaves room for confusion on two fronts: a) initial = zeroth or first. It seems you mean first, but could be understood the other way. b) it is a relative size (to the zeroth generation). 

*We have updated the definition to be the relative generation size as it is a relative size to the previous generation (i.e. generation $i$ is based on generation $i - 1$).*

- Model description in SI. While much clearer in the article, I'm still a bit confused by the equations in the start of the SI. Could these be explained? I don't really understand what the first equation is meant to mean: eg what does 'current' mean (is it the notifications in a year with data, to be matched to data?)? How do you distinguish notifications as primary vs secondary (and if defined by model dynamics, how is the initial split determined)? Why are x and f making an appearance? For the second equation, why is a fraction (1-fx) of the current propagated and why is this multiplied by this decline factor? In the first instance, x already captures information about decline. In the second instance, the power L-Z is mysterious to me (I was expecting a power like L/z to count generations, with little z rather than Z). 

*We agree that this could have been better explained. Hopefully, our changes from your above points add some clarity about what is being modelled. The aim of this step is to allocate secondary notifications to either the current year being considered or the subsequent modelled time step (5 years in the future). This was found to be neccessary in order to reproduce Sutherland et al.'s final results table but does not impact the overall model results and so is only used for model validation purposes (as is hopefully now clear from the paper). We updated the description of these equations in the SI in order to provide more context.*


MINUTIAE 

*Thanks for highlighting the JVCI typo along with the other issues outlined below. We have thoroughly checked the manuscript and corrected the remaining misspellings. We have also dealt with your other points as suggested.* 

- I would note that the typo 'JVCI' picked up by another reviewer still occurs in many places, including Figure captions 

- LOESS makes an appearance as LEOSS 

- 'DHSS' appears before definition 

- "13 year old's" 

- 'can not': more usual to have cannot 

- In various places (eg line 12 page 6): 'decay of 9% in notification rates' - need to specify annual or per year every time.

